version: 2.1

executors:
  windows-medium:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.medium
    shell: bash.exe

orbs:
  docker: circleci/docker@1.7.0
  windows: circleci/windows@2.4.1
  
jobs:
  untar_bz2:
    executor: windows-medium
    steps:
      - run:
          name: Download tar file (BZ2)
          command: |
            curl -s https://example-files.online-convert.com/archive/bz2/example.tar.bz2 > example.tar.bz2
      - run:
          name: Untar
          command: |
            tar jxvf example.tar.bz2
            # there should be a PDF file extracted
            ls -laH example.pdf
  check_docker:
    executor: windows/default
    steps:
      - checkout
      - run:
          name: check last commit details
          command: |
            # See PRETTY FORMATS section for pretty format options
            # https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-log.html#:~:text=PRETTY-,FORMATS,-If%20the%20commit
            LAST_COMMIT="$(git log -n 1 --pretty=format:"%ad" --date=iso)"
            echo $LAST_COMMIT
      - run:
          name: verify user
          command: |
            whoami
      - run:
          name: check Docker version
          command: |
            docker --version
            docker info
      - run:
          name: check folder permissions
          command: |
            Dir C:\Users\circleci\project | Get-Acl
#       - run:
#           name: inspect Docker image
#           command: |
#             docker pull docker.io/collectionpartnersolutions/legacy
#             docker image inspect collectionpartnersolutions/legacy | jq ".[0]"
#       - run:
#           name: verify C drive mountable
#           command: |
#             docker run -v C:\Users\circleci\project:C:\Source collectionpartnersolutions/legacy
workflows:
  main:
    jobs:
#       - check_docker
      - untar_bz2
 
